import { useState } from 'react';
import { Layers, RotateCw, Check, X, Sparkles } from 'lucide-react';
import toast from 'react-hot-toast';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import Badge from '../components/Badge';

const Flashcards = () => {
  const [selectedDeck, setSelectedDeck] = useState(1);
  const [cardIdx, setCardIdx] = useState(0);
  const [flipped, setFlipped] = useState(false);

  const decks = [
    {
      id: 1,
      name: 'Calculus III Integrals',
      subject: 'MATH 301',
      cards: [
        { front: 'Formula for Greens Theorem?', back: '∫_C (P dx + Q dy) = ∬_D (∂Q/∂x - ∂P/∂y) dA' },
        { front: 'What is a conservative vector field?', back: 'A field F where F = ∇f for some scalar function f.' },
        { front: 'Definition of divergence?', back: 'div F = ∇ • F (flux per unit volume leaving a point)' },
      ],
    },
    {
      id: 2,
      name: 'Quantum Physics Postulates',
      subject: 'PHYS 410',
      cards: [
        { front: 'What is a state vector?', back: 'A complete mathematical description of a quantum system, denoted by |ψ⟩.' },
        { front: 'What represents observable quantities?', back: 'Self-adjoint (Hermitian) operators acting on Hilbert space.' },
      ],
    },
  ];

  const currentDeck = decks.find((d) => d.id === selectedDeck) || decks[0];
  const currentCard = currentDeck.cards[cardIdx];

  const handleNext = (known) => {
    if (known) {
      toast.success('Nice job! Marked as Known.');
    } else {
      toast.error('Marked for revision.');
    }
    setFlipped(false);
    setTimeout(() => {
      if (cardIdx + 1 < currentDeck.cards.length) {
        setCardIdx(cardIdx + 1);
      } else {
        setCardIdx(0);
        toast('Deck complete! Starting over.', { icon: '🔄' });
      }
    }, 150);
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Flashcards"
        subtitle="Spaced repetition decks generated by AI to enhance active recall."
        icon={Layers}
      />

      <div className="grid gap-6 lg:grid-cols-4">
        {/* Decks Column */}
        <div className="glass-card p-4 space-y-3">
          <span className="text-xs font-bold text-gray-400 uppercase tracking-wider block border-b border-white/5 pb-2">
            DECKS
          </span>
          <div className="space-y-2">
            {decks.map((deck) => (
              <button
                key={deck.id}
                onClick={() => {
                  setSelectedDeck(deck.id);
                  setCardIdx(0);
                  setFlipped(false);
                }}
                className={`w-full text-left p-3 rounded-xl border transition cursor-pointer ${
                  selectedDeck === deck.id
                    ? 'border-brand-500 bg-brand-500/10'
                    : 'border-white/5 bg-white/[0.01] hover:bg-white/[0.03]'
                }`}
              >
                <span className="text-[10px] text-brand-300 font-semibold">{deck.subject}</span>
                <h4 className="font-semibold text-sm text-white mt-0.5">{deck.name}</h4>
                <p className="text-[10px] text-gray-500 mt-1">{deck.cards.length} Cards</p>
              </button>
            ))}
          </div>
        </div>

        {/* Card Viewer */}
        <div className="lg:col-span-3 flex flex-col items-center justify-center py-10">
          <div
            onClick={() => setFlipped(!flipped)}
            className="w-full max-w-md h-64 relative perspective-1000 cursor-pointer group"
          >
            <div
              className={`w-full h-full rounded-2xl border border-white/70 dark:border-white/10 bg-white/80 dark:bg-slate-900/85 text-[#241b4b] dark:text-white p-8 shadow-2xl flex flex-col items-center justify-center text-center transition-all duration-500 preserve-3d ${
                flipped ? 'rotate-y-180' : ''
              }`}
            >
              {/* Front side */}
              <div className={`absolute inset-0 p-8 flex flex-col justify-between backface-hidden ${flipped ? 'opacity-0' : 'opacity-100'}`}>
                <div className="flex justify-between items-center text-xs text-gray-500">
                  <span>Front</span>
                  <Badge color="blue">{cardIdx + 1} / {currentDeck.cards.length}</Badge>
                </div>
                <p className="text-base sm:text-lg font-semibold text-[#241b4b] dark:text-white my-auto">
                  {currentCard.front}
                </p>
                <div className="text-xs text-gray-500 flex items-center justify-center gap-1">
                  <RotateCw className="h-3 w-3" /> Click card to flip
                </div>
              </div>

              {/* Back side */}
              <div className={`absolute inset-0 p-8 flex flex-col justify-between backface-hidden rotate-y-180 ${flipped ? 'opacity-100' : 'opacity-0'}`}>
                <div className="flex justify-between items-center text-xs text-brand-300">
                  <span>Back</span>
                  <Badge color="purple">Solution</Badge>
                </div>
                <p className="text-sm sm:text-base font-mono text-[#6b6388] dark:text-slate-300 my-auto leading-relaxed">
                  {currentCard.back}
                </p>
                <div className="text-xs text-gray-500 flex items-center justify-center gap-1">
                  <RotateCw className="h-3 w-3" /> Click card to flip
                </div>
              </div>
            </div>
          </div>

          {/* Action buttons */}
          {flipped && (
            <div className="flex gap-4 mt-6">
              <Button onClick={() => handleNext(false)} variant="danger" className="gap-1 px-5">
                <X className="h-4 w-4" /> Forgot
              </Button>
              <Button onClick={() => handleNext(true)} variant="success" className="gap-1 px-5">
                <Check className="h-4 w-4" /> I knew it
              </Button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Flashcards;
